name: [OMNIA] SLSA Builder V1.0

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build Universal Engine
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Compile Omni-Drive Engine
        run: cargo build --release

      - name: Generate SLSA Hashes
        id: hash
        run: |
          cd target/release
          mv omnia omnia-engine || true
          echo "hashes=$(sha256sum omnia-engine | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: omnia-engine
          path: target/release/omnia-engine

  provenance:
    needs: [build]
    name: Generate Cryptographic Certificate
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
